In [1]:
import numpy as np

In [2]:
# обратная матрица - все ок
A1=np.array([[1,2,3],[4,5,6],[7,8,10]])
print('A1:\n',A1)

A1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [3]:
print('rk(A3):\n',np.linalg.matrix_rank(A1))

rk(A3):
 3


In [ ]:
# обратная матрица - все ок
A1_inv=np.linalg.inv(A1)
print('A1 inversed:\n',A1_inv)


In [ ]:
# обратная матрица - все ок
print('A1 @ A1 inversed=E check:\n',A1@A1_inv,1)
print(np.round(A1@A1_inv,1))
print('check OK')

In [ ]:
# обратная матрица - вырожденный случай
A2=np.array([[1,2,3],[4,5,6],[1,2,3]])
print('A2:\n',A2)

In [ ]:
# обратная матрица - вырожденный случай
print('rk(A3):\n',np.linalg.matrix_rank(A2))

In [ ]:
# обратная матрица - вырожденный случай
np.linalg.inv(A2)

In [ ]:
# обратная матрица - magic
A3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A3:\n',A3)

In [ ]:
# обратная матрица - magic
print('rk(A3):\n',np.linalg.matrix_rank(A3))

In [ ]:
# обратная матрица - magic
print('A3 inversed:\n',np.linalg.inv(A3))

In [ ]:
# обратная матрица - magic
print('A3 @ A3 inversed = E check:\n',A3@np.linalg.inv(A3))
print('check failed')

In [ ]:
print('det(A1)):\n',np.linalg.det(A1))

In [ ]:
print('det(A2)):\n',np.linalg.det(A2))

In [ ]:
print('det(A3)):\n',np.linalg.det(A3))

In [ ]:
# обратная матрица - неустойчивость
A4=np.array([[1,2,3],[4,5,6],[1,2,3.00005]])
print('A4:\n',A4)
print('rk(A4):\n',np.linalg.matrix_rank(A4))
print('det(A4):\n',np.linalg.det(A4))
print('A4 inverse:\n',np.linalg.inv(A4))

In [ ]:
# обратная матрица - неустойчивость вблизи нулевого определителя
A5=np.array([[1,2,3],[4,5,6],[1,2,3.00000005]])
print('A5:\n',A5)
print('rk(A5):\n',np.linalg.matrix_rank(A5))
print('det(A5):\n',np.linalg.det(A5))
print('A5 inverse:\n',np.linalg.inv(A5))

In [ ]:
# обратимость матрицы Грама линейно независимой системы векторов
v1=np.array([1,2,1])
v2=np.array([1,1,1])
A=np.array([v1,v2]).T
print('A:\n',A)
print('Матрица Грама:\n',A.T@A)

In [ ]:
print('Ранг матрицы Грама:\n',np.linalg.matrix_rank(A.T@A))

In [ ]:
print('Определитель матрицы Грама:\n',np.linalg.det(A.T@A))

In [ ]:
print('Обратная к матрице Грама:\n',np.linalg.inv(A.T@A))

In [4]:
A=np.array( [[ 8 , 6 ,11],[ 7 , 5 , 9],[ 6 ,10,  6]])

In [5]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [6]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])


In [7]:
A = np.array([v1,v2,v3,v4])

In [8]:
A

array([[ 9, 10,  7,  7,  9],
       [ 2,  0,  5,  1,  4],
       [ 4,  0,  0,  4,  1],
       [ 3, -4,  3, -1, -4]])

In [9]:
np.linalg.matrix_rank(A)

4

In [13]:
A_G = A@A.T

In [16]:
np.linalg.inv(A_G)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [17]:
A = np.array([[1,2],
              [-3,1],
             [1,2],
             [1,-1]])

In [19]:
np.linalg.inv(A.T@A)

array([[0.08333333, 0.        ],
       [0.        , 0.1       ]])

In [20]:
b = [1,4,5,0]

In [21]:
A.T@b

array([-6, 16])

In [22]:
np.linalg.inv(A.T@A)@(A.T@b)

array([-0.5,  1.6])

In [23]:
-29.3-0.26*0.2+8.4*6

21.048000000000005

In [45]:
x1 = np.array([11,8])

In [46]:
x1_c = x1 -np.mean(x1)
x1_n= np.linalg.norm(x1_c)

In [47]:
(1/x1_n)*x1_c

array([ 0.70710678, -0.70710678])