In [2]:
import numpy as np
A = np.array([[1, 0.9922],
        [0.9922, 1]]) # создаем матрицу 3х3 
B = np.linalg.eig(A) # находим собственные вектора (с.в.) и собственные числа (с.ч.) через np.linalg.eig
B
# Обратите внимание, что B - кортеж (tuple). Его компоненты имеют тип np.ndarray, с которыми вы уже должны быть знакомы. 
# Нулевая компонента B[0] - вектор собственных чисел, а компонента B[1] - матрица, столбцами которой являются 
# собственные вектора, соответствующие данному числу.; в данном случае собственному числу 13.59373746 
# соответствует собственный вектор [0.45145779, 0.62348353, 0.63832135]

(array([1.9922, 0.0078]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [4]:
X1 = np.array([1, 2, 1, 1])
X2 = np.array([70,130,65,60])


array([50.20458146, 93.33809512, 46.66904756, 43.13351365])

In [13]:
X1_c = X1- X1.mean()
X2_c = X2- X2.mean()


In [14]:
X1_norm = np.linalg.norm(X1_c)
X2_norm = np.linalg.norm(X2_c)

In [15]:
X1_st = X1_c/X1_norm
X2_st = X2_c/X2_norm

In [25]:
New = B[1][1][0]*X1_st+B[1][1][1]*X2_st

In [30]:
New/np.linalg.norm(New)

array([-0.24396044,  0.86433557, -0.28811186, -0.33226327])

In [22]:
New

array([-1.,  1., -1., -1.])