In [33]:
import pandas as pd
import numpy as np

In [3]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [4]:
A

array([[ 6, 10,  9],
       [ 9, 10, 10],
       [10,  8,  7]])

In [5]:
B

array([[ 0, -1,  0],
       [-1,  1, -1],
       [ 3, -2,  3]])

In [6]:
# Поэлементное умножение
A*B

array([[  0, -10,   0],
       [ -9,  10, -10],
       [ 30, -16,  21]])

In [7]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[ 17 -14  17]
 [ 20 -19  20]
 [ 13 -16  13]]


In [8]:
# Матричное умножение
np.dot(A,B)

array([[ 17, -14,  17],
       [ 20, -19,  20],
       [ 13, -16,  13]])

In [9]:
# Матричное умножение
A@B

array([[ 17, -14,  17],
       [ 20, -19,  20],
       [ 13, -16,  13]])

In [10]:
# Порядок умножения AB != BA
B@A

array([[ -9, -10, -10],
       [ -7,  -8,  -6],
       [ 30,  34,  28]])

In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[11  5 11  7 11]
 [ 9  7  9  5 11]
 [ 7 10  6 11  8]]
B:
 [[ 1  3]
 [ 1 -2]
 [ 3  2]
 [-1  1]
 [ 3  3]]


In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[75, 85],
       [71, 69],
       [48, 48]])

In [13]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [14]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [ ]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

In [ ]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

In [ ]:
b@A

In [ ]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

In [ ]:
# матрица Грама ортогональной системы векторов
A@A.T

In [ ]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

In [ ]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

In [ ]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

In [15]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [16]:
A@x

array([26, 30])

In [17]:
A=np.array( [ [1,9,8,5] , [3,6,3,2] , [3,3,3,3], [0,2,5,9], [4,4,1,2] ] )
B=np.array( [ [1,-1,0,1,1] , [-2,0,2,-1,1] ] )

In [19]:
A

array([[1, 9, 8, 5],
       [3, 6, 3, 2],
       [3, 3, 3, 3],
       [0, 2, 5, 9],
       [4, 4, 1, 2]])

In [25]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [26]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [27]:
X = np.array([x, y, z])

In [30]:
X@X.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [34]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [42]:
df = Count_DF*Price_DF

In [44]:
com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [48]:
res = (df*com).sum(axis=1)

In [50]:
res.values

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [62]:
com_2 = np.ones(5)-com

In [63]:
res_2 = (df*com_2).sum(axis=1)

In [64]:
res_2.values

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [65]:
1/8

0.125

In [66]:
A=np.array( [[ 8 , 6 ,11],[ 7 , 5 , 9],[ 6 ,10,  6]])